alias GA='git add '
alias SS = 'eval `ssh-agent` && ssh-add'
alias GC='git commit -m "fix"'
alias GS='git status'
alias WK='cd ../../vagrant/'
alias GP='git push'
alias ggcw='gcc -Wall -Werror -Wextra -pedantic '
